### ISSUE TITLE
error while trying to destroy document: Invalid rev format

### ISSUE THREAD

**Issue by jfhbrook** [dscape/futoncli#14]
```
josh@onix:~$ futon document destroy user/jhizzle
info:    Welcome to futon
info:    It worked if it ends with futon ok
info:    Executing command document destroy user/jhizzle
error:   Error running command document destroy user/jhizzle
error:   Unspecified error
data:    
data:    {
data:        request: {
data:            uri: 'http:/whatever/database/user%2Fjhizzle?rev=',
data:            headers: { content-type: 'application/json', accept: 'application/json' },
data:            jar: false,
data:            callback: [Function],
data:            method: 'DELETE'
data:        },
data:        description: 'Unspecified error',
data:        headers: {
data:            uri: 'http:/whatever/database/user%2Fjhizzle?rev=',
data:            content-type: 'application/json',
data:            cache-control: 'must-revalidate',
data:            date: 'Fri, 27 Jul 2012 05:17:42 GMT',
data:            status-code: 400
data:        },
data:        scope: 'couch',
data:        reason: 'Invalid rev format',
data:        errid: 'non_200',
data:        status-code: 400,
data:        status_code: 400,
data:        name: 'Error',
data:        error: 'bad_request',
data:        stacktrace: [
data:            'Error: Unspecified error',
data:            '    at Request._callback (/usr/local/lib/node_modules/futon/node_modules/nano/nano.js:288:39)',
data:            '    at Request.init.self.callback (/usr/local/lib/node_modules/futon/node_modules/nano/node_modules/request/main.js:120:22)',
data:            '    at Request.EventEmitter.emit (events.js:91:17)',
data:            '    at Request.<anonymous> (/usr/local/lib/node_modules/futon/node_modules/nano/node_modules/request/main.js:555:16)',
data:            '    at Request.EventEmitter.emit (events.js:88:17)',
data:            '    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/usr/local/lib/node_modules/futon/node_modules/nano/node_modules/request/main.js:517:14)',
data:            '    at IncomingMessage.EventEmitter.emit (events.js:115:20)',
data:            '    at IncomingMessage._emitEnd (http.js:366:10)',
data:            '    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)'
data:        ]
data:    }
data:    
info:    futon not ok
```

My guess is that either this command should grab the latest "rev" parameter automatically, or that it should guard against this case and explain how to use `futon document get user/jhizzle` to get the rev.

What do you think?

**Comment by jfhbrook** [comment]
Digging into the code, I see what the intent is now, but this surprised me:

```
/* arguments: */ { '0': 'user/jhizzle', '1': null, '2': [Function] }
```

I need to figure out how/why the callback is in '2' instead of '1' now, and then I can probably fix this.

**Comment by jfhbrook** [comment]
Okay, I think what happened is that the cli router is being smart about assuming that the last argument is a callback. That's certainly how it's behaving now.

That means there are probably other places here where it's assumed the router doesn't behave this way.

**Comment by dscape** [comment]
Did you fix this? Or?

I would like to know if you expect me to act on this? :)

**Comment by jfhbrook** [comment]
I can fix it if you don't mind waiting. It's just so weird though! It's gonna bug me until I know when/how/why the currying is behaving weird.

**Comment by dscape** [comment]
This is correct behavior, you didnt specify a `rev=foobar` and that is the reply couch gives you.

We could add a warning to the command saying "you need to specify rev", feel free to send that as a PR if you feel strongly about it
